@startuml プロジェクト開発
left to right direction
actor 社員 #DDDDDD;line:black;line.bold;
actor 管理者 #DDDDDD;line:black;line.bold;
rectangle 勤怠管理システム {

    usecase 自身の出退勤状況確認
    usecase 残業申請
    usecase 社員証読み取り
    usecase 通知
    usecase 残業報告

    usecase 社員新規登録
    usecase 全社員出退勤の確認
    usecase 社員検索機能
    usecase 社員勤務状況一覧
    usecase 残業申請の承認or拒否

}
社員 --> 社員証読み取り
社員 --> 自身の出退勤状況確認
社員 --> 残業申請
社員 --> 残業報告

社員証読み取り <-- 管理者
自身の出退勤状況確認 <-- 管理者
社員新規登録 <-- 管理者
全社員出退勤の確認 <-- 管理者
社員検索機能 <-- 管理者
社員勤務状況一覧 <-- 管理者
残業申請 <-- 管理者
残業申請の承認or拒否 <-- 管理者
残業報告 <-- 管理者

@enduml