@startuml 診察予約
left to right direction
actor ユーザー #DDDDDD;line:black;line.bold;
actor 看護師 #DDDDDD;line:black;line.bold;

rectangle 予約システム {
  usecase (メニュー)
  usecase (予約と確認)
  usecase (あなたの順番)
  usecase (今の順番)
  ユーザー --> (メニュー)
  ユーザー --> (予約と確認)
  ユーザー --> (あなたの順番)
  ユーザー --> (今の順番)
  (今の順番) <-- 看護師

}

@enduml
